>P1;1ctqA
structureX:1ctq:   1 :A: 166 :A:MOL_ID  1;  MOLECULE  TRANSFORMING PROTEIN P21/H-RAS-1;  CHAIN  A;  FRAGMENT  R:MOL_ID  1;  ORGANISM_SCIENTIFIC  HOMO SAPIENS;  ORGANISM_COMMON  HUMAN;  EXPRES: 1.26:-1.00
MTEYKLVVVGAGGVGKSALTIQLIQNHFVDEYDPTIEDSYRKQVVIDGETCLLDILDTAGQEEYSAMRDQYMRTG
EGFLCVFAINNTKSFEDIHQYREQIKRVKDSDDVPMVLVGNKCDLAARTVESRQAQDLARSYGIPYIETSAKTRQ
GVEDAFYTLVREIRQH*
>P1;1cz0A
structureX:1cz0:   2 :A: 163 :A:MOL_ID  1;  MOLECULE  INTRON-ENCODED HOMING ENDONUCLEASE I-PPOI;  CHAIN  A, B;:MOL_ID  1;  ORGANISM_SCIENTIFIC  PHYSARUM POLYCEPHALUM;  EXPRESSION_SYSTEM  ESC: 2.10:-1.00
ALTNAQILAVIDSWEETVGQFPVITHHVPLGGGLQGTLHCYEIPLAAPYGVGFAKNGPTRWQYKRTINQVVHRWG
SHTVPFLLEPDNINGKTCTASHLCHNTRCHNPLHLCWESLDDNKGRNWCPGPNGGCVHAVVCLRQGPLYGPGATV
AGPQQRGSHFVV*
>P1;1c5hA
structureX:1c5h:   1 :A: 185 :A:MOL_ID  1;  MOLECULE  ENDO-1,4-BETA-XYLANASE;  CHAIN  A;  FRAGMENT  CATALYTIC D:MOL_ID  1;  ORGANISM_SCIENTIFIC  BACILLUS CIRCULANS;  ORGANISM_COMMON  BACTERIA: 1.55:-1.00
ASTDYWQNWTDGGGIVNAVNGSGGNYSVNWSNTGDFVVGKGWTTGSPFRTINYNAGVWAPNGNGYLTLYGWTRSP
LIEYYVVDSWGTYRPTGTYKGTVKSDGGTYDIYTTTRYNAPSIDGDRTTFTQYWSVRQSKRPTGSNATITFTNHV
NAWKSHGMNLGSNWAYQVMATEGYQSSGSSNVTVW*
>P1;8icfA
structureX:8icf:   9 :A: 335 :A:MOL_ID  1;  MOLECULE  DNA POLYMERASE BETA;  CHAIN  A;  EC  2.7.7.7;  ENGINEERED:MOL_ID  1;  ORGANISM_SCIENTIFIC  HOMO SAPIENS;  ORGANISM_COMMON  HUMAN;  EXPRES: 2.90:-1.00
ETLNGGITDMLTELANFEKNVSQAIHKYNAYRKAASVIAKYPHKIKSGAEAKKLPGVGTKIAEKIDEFLATGKLR
KLEKIRQDDTSSSINFLTRVSGIGPSAARKFVDEGIKTLEDLRKNEDKLNHHQRIGLKYFGDFEKRIPREEMLQM
QDIVLNEVKKVDSEYIATVCGSFRRGAESSGDMDVLLTHPSFTSESTKQPKLLHQVVEQLQKVHFITDTLSKGET
KFMGVCQLPSKNDEKEYPHRRIDIRLIPKDQYYCGVLYFTGSDIFNKNMRAHALEKGFTINEYTIRPLGVTGVAG
EPLPVDSEKDIFDYIQWKYREPKDRSE*
>P1;8icvA
structureX:8icv:   9 :A: 335 :A:MOL_ID  1;  MOLECULE  DNA POLYMERASE BETA;  CHAIN  A;  EC  2.7.7.7;  ENGINEERED:MOL_ID  1;  ORGANISM_SCIENTIFIC  HOMO SAPIENS;  ORGANISM_COMMON  HUMAN;  EXPRES: 3.20:-1.00
ETLNGGITDMLTELANFEKNVSQAIHKYNAYRKAASVIAKYPHKIKSGAEAKKLPGVGTKIAEKIDEFLATGKLR
KLEKIRQDDTSSSINFLTRVSGIGPSAARKFVDEGIKTLEDLRKNEDKLNHHQRIGLKYFGDFEKRIPREEMLQM
QDIVLNEVKKVDSEYIATVCGSFRRGAESSGDMDVLLTHPSFTSESTKQPKLLHQVVEQLQKVHFITDTLSKGET
KFMGVCQLPSKNDEKEYPHRRIDIRLIPKDQYYCGVLYFTGSDIFNKNMRAHALEKGFTINEYTIRPLGVTGVAG
EPLPVDSEKDIFDYIQWKYREPKDRSE*
>P1;9icfA
structureX:9icf:   9 :A: 335 :A:MOL_ID  1;  MOLECULE  DNA POLYMERASE BETA;  CHAIN  A;  EC  2.7.7.7;  ENGINEERED:MOL_ID  1;  ORGANISM_SCIENTIFIC  HOMO SAPIENS;  ORGANISM_COMMON  HUMAN;  EXPRES: 3.00:-1.00
ETLNGGITDMLTELANFEKNVSQAIHKYNAYRKAASVIAKYPHKIKSGAEAKKLPGVGTKIAEKIDEFLATGKLR
KLEKIRQDDTSSSINFLTRVSGIGPSAARKFVDEGIKTLEDLRKNEDKLNHHQRIGLKYFGDFEKRIPREEMLQM
QDIVLNEVKKVDSEYIATVCGSFRRGAESSGDMDVLLTHPSFTSESTKQPKLLHQVVEQLQKVHFITDTLSKGET
KFMGVCQLPSKNDEKEYPHRRIDIRLIPKDQYYCGVLYFTGSDIFNKNMRAHALEKGFTINEYTIRPLGVTGVAG
EPLPVDSEKDIFDYIQWKYREPKDRSE*
>P1;9icvA
structureX:9icv:   9 :A: 335 :A:MOL_ID  1;  MOLECULE  DNA POLYMERASE BETA;  CHAIN  A;  EC  2.7.7.7;  ENGINEERED:MOL_ID  1;  ORGANISM_SCIENTIFIC  HOMO SAPIENS;  ORGANISM_COMMON  HUMAN;  EXPRES: 2.70:-1.00
ETLNGGITDMLTELANFEKNVSQAIHKYNAYRKAASVIAKYPHKIKSGAEAKKLPGVGTKIAEKIDEFLATGKLR
KLEKIRQDDTSSSINFLTRVSGIGPSAARKFVDEGIKTLEDLRKNEDKLNHHQRIGLKYFGDFEKRIPREEMLQM
QDIVLNEVKKVDSEYIATVCGSFRRGAESSGDMDVLLTHPSFTSESTKQPKLLHQVVEQLQKVHFITDTLSKGET
KFMGVCQLPSKNDEKEYPHRRIDIRLIPKDQYYCGVLYFTGSDIFNKNMRAHALEKGFTINEYTIRPLGVTGVAG
EPLPVDSEKDIFDYIQWKYREPKDRSE*
>P1;4znf
structureN:4znf:   1 : :  30 : :ZINC FINGER (/NMR$):HUMAN (HOMO $SAPIENS) ENHANCER BINDING PROTEIN:-1.00:-1.00
RPYHCSYCNFSFKTKGNLTKHMKSKAHSKK*
>P1;4rhv1
structureX:4rhv:  17 :1: 289 :1:RHINOVIRUS 14 (/HRV$14):HUMAN (HOMO $SAPIENS) VIRUS GROWN IN HE*LA CELLS: 3.00:-1.00
TVASISSGPKHTQKVPILTANETGATMPVLPSDSIETRTTYMHFNGSETDVECFLGRAACVHVTEIQNKDATGID
NHREAKLFNDWKINLSSLVQLRKKLELFTYVRFDSEYTILATASQPDSANYSSNLVVQAMYVPPGAPNPKEWDDY
TWQSASNPSVFFKVGDTSRFSVPYVGLASAYNCFYDGYSHDDAETQYGITVLNHMGSMAFRIVNEHDEHKTLVKI
RVYHRAKHVEAWIPRAPRALPYTSIGRTNYPKNTEPVIKKRKGDIKSY*
>P1;4rhv2
structureX:4rhv:   8 :2: 262 :2:RHINOVIRUS 14 (/HRV$14):HUMAN (HOMO $SAPIENS) VIRUS GROWN IN HE*LA CELLS: 3.00:-1.00
GYSDRVQQITLGNSTITTQEAANAVVCYAEWPEYLPDVDASDVNKTSKPDTSVCRFYTLDSKTWTTGSKGWCWKL
PDALKDMGVFGQNMFFHSLGRSGYTVHVQCNATKFHSGCLLVVVIPEHQLASHEGGNVSVKYTFTHPGERGIDLS
SANEVGGPVKDVLYNMNGTLLGNLLIFPHQFINLRTNNTATIVIPYINSVPIDSMTRHNNVSLMVIPIAPLTVPT
GATPSLPITVTIAPMCTEFSGIRSKSIVPQ*
>P1;4rhv3
structureX:4rhv:   1 :3: 236 :3:RHINOVIRUS 14 (/HRV$14):HUMAN (HOMO $SAPIENS) VIRUS GROWN IN HE*LA CELLS: 3.00:-1.00
GLPTTTLPGSGQFLTTDDRQSPSALPNYEPTPRIHIPGKVHNLLEIIQVDTLIPMNNTHTKDEVNSYLIPLNANR
QNEQVFGTNLFIGDGVFKTTLLGEIVQYYTHWSGSLRFSLMYTGPALSSAKLILAYTPPGARGPQDRREAMLGTH
VVWDIGLQSTIVMTIPWTSGVQFRYTDPDTYTSAGFLSCWYQTSLILPPETTGQVYLLSFISACPDFKLRLMKDT
QTISQTVALTE*
>P1;4rhv4
structureX:4rhv:  29 :4:  68 :4:RHINOVIRUS 14 (/HRV$14):HUMAN (HOMO $SAPIENS) VIRUS GROWN IN HE*LA CELLS: 3.00:-1.00
INYYKDAASTSSAGQSLSMDPSKFTEPVKDLMLKGAPALN*
>P1;4sbvA
structureX:4sbv:  62 :A: 260 :A:SOUTHERN BEAN MOSAIC VIRUS COAT PROTEIN:SOUTHERN BEAN MOSAIC VIRUS (COW PEA STRAIN): 2.80:-1.00
SSMDVTILSHCELSTELAVTVTIVVTSELVMPFTVGTWLRGVAQNWSKYAWVAIRYTYLPSCPTTTSGAIHMGFQ
YDMADTLPVSVNQLSNLKGYVTGPVWEGQSGLCFVNNTKCPDTSRAITIALDTNEVSEKRYPFKTATDYATAVGV
NANIGNILVPARLVTAMEGGSSKTAVNTGRLYASYTIRLIEPIAAALNL*
>P1;4sbvB
structureX:4sbv:  62 :B: 260 :B:SOUTHERN BEAN MOSAIC VIRUS COAT PROTEIN:SOUTHERN BEAN MOSAIC VIRUS (COW PEA STRAIN): 2.80:-1.00
SSMDVTILSHCELSTELAVTVTIVVTSELVMPFTVGTWLRGVAQNWSKYAWVAIRYTYLPSCPTTTSGAIHMGFQ
YDMADTLPVSVNQLSNLKGYVTGPVWEGQSGLCFVNNTKCPDTSRAITIALDTNEVSEKRYPFKTATDYATAVGV
NANIGNILVPARLVTAMEGGSSKTAVNTGRLYASYTIRLIEPIAAALNL*
>P1;4sbvC
structureX:4sbv:  39 :C: 260 :C:SOUTHERN BEAN MOSAIC VIRUS COAT PROTEIN:SOUTHERN BEAN MOSAIC VIRUS (COW PEA STRAIN): 2.80:-1.00
QAGVSMAPIAQGTMVKLRPPMLRSSMDVTILSHCELSTELAVTVTIVVTSELVMPFTVGTWLRGVAQNWSKYAWV
AIRYTYLPSCPTTTSGAIHMGFQYDMADTLPVSVNQLSNLKGYVTGPVWEGQSGLCFVNNTKCPDTSRAITIALD
TNEVSEKRYPFKTATDYATAVGVNANIGNILVPARLVTAMEGGSSKTAVNTGRLYASYTIRLIEPIAAALNL*
>P1;4phvA
structureX:4phv:   1 :A:  99 :A:HUMAN IMMUNODEFICIENCY VIRUS TYPE 1 (HIV-1) PROTEASE COMPLEX  WITH N,N-BIS(2(R):HUMAN (HOMO SAPIENS) IMMUNODEFICIENCY VIRUS TYPE 1  PROTEASE (NY5 ISOLATE) RECO: 2.10:-1.00
PQITLWQRPLVTIKIGGQLKEALLDTGADDTVLEEMNLPGRWKPKMIGGIGGFIKVRQYDQILIEICGHKAIGTV
LVGPTPVNIIGRNLLTQIGCTLNF*
>P1;4phvB
structureX:4phv:   1 :B:  99 :B:HUMAN IMMUNODEFICIENCY VIRUS TYPE 1 (HIV-1) PROTEASE COMPLEX  WITH N,N-BIS(2(R):HUMAN (HOMO SAPIENS) IMMUNODEFICIENCY VIRUS TYPE 1  PROTEASE (NY5 ISOLATE) RECO: 2.10:-1.00
PQITLWQRPLVTIKIGGQLKEALLDTGADDTVLEEMNLPGRWKPKMIGGIGGFIKVRQYDQILIEICGHKAIGTV
LVGPTPVNIIGRNLLTQIGCTLNF*
>P1;4tgf
structureN:4tgf:   1 : :  50 : :DES-VAL==1==,VAL==2==-TRANSFORMING GROWTH FACTOR ALPHA  (/TGF$$A):HUMAN (HOMO $SAPIENS):-1.00:-1.00
VVSHFNDCPDSHTQFCFHGTCRFLVQEDKPACVCHSGYVGARCEHADLLA*
>P1;4tsvA
structureX:4tsv:  10 :A: 157 :A:MOL_ID  1;  MOLECULE  TUMOR NECROSIS FACTOR-ALPHA;  CHAIN  A;  ENGINEERED  YES;:MOL_ID  1;  ORGANISM_SCIENTIFIC  HOMO SAPIENS;  ORGANISM_COMMON  HUMAN;  EXPRES: 1.80:-1.00
DKPVAHVVANPQAEGQLQWSNRRANALLANGVELRDNQLVVPIEGLFLIYSQVLFKGQGCPSTHVLLTHTISRIA
VSYQTKVNLLSAIKSPCQRETPEGAEAKPWYEPIYLGGVFQLEKGDRLSAEINRPDYLDFAESGQVYFGIIAL*
>P1;4kiv
structureX:4kiv:   0 : :  80 : :MOL_ID  1;  MOLECULE  APOLIPOPROTEIN;  CHAIN  NULL;  FRAGMENT  KRINGLE IV-10;:MOL_ID  1;  ORGANISM_SCIENTIFIC  HOMO SAPIENS;  ORGANISM_COMMON  HUMAN;  EXPRES: 2.20:-1.00
QCYHGNGQSYRGTFSTTVTGRTCQSWSSMTPHRHQRTPENYPNDGLTMNYCRNPDADTGPWCFTMDPSIRREYCN
LTRC*
>P1;4cevA
structureX:4cev:   2 :A: 299 :A:MOL_ID  1;  MOLECULE  ARGINASE;  CHAIN  A, B, C, D, E, F;  EC  3.5.3.1;  ENGINE:MOL_ID  1;  ORGANISM_SCIENTIFIC  BACILLUS CALDOVELOX;  STRAIN  BACILLUS SPECIES: 2.70:-1.00
KPISIIGVPMDLGQTRRGVDMGPSAMRYAGVIERLERLHYDIEDLGDIPIGKAERLHEQGDSRLRNLKAVAEANE
KLAAAVDQVVQRGRFPLVLGGDHSIAIGTLAGVAKHYERLGVIWYDAHGDVNTAETSPSGNIHGMPLAASLGFGH
PALTQIGGYSPKIKPEHVVLIGVRSLDEGEKKFIREKGIKIYTMHEVDRLGMTRVMEETIAYLKERTDGVHLSLD
LDGLDPSDAPGVGTPVIGGLTYRESHLAMEMLAEAQIITSAEFVEVNPILDERNKTASVAVALMGSLFGEKLM*
>P1;4cevB
structureX:4cev:   2 :B: 299 :B:MOL_ID  1;  MOLECULE  ARGINASE;  CHAIN  A, B, C, D, E, F;  EC  3.5.3.1;  ENGINE:MOL_ID  1;  ORGANISM_SCIENTIFIC  BACILLUS CALDOVELOX;  STRAIN  BACILLUS SPECIES: 2.70:-1.00
KPISIIGVPMDLGQTRRGVDMGPSAMRYAGVIERLERLHYDIEDLGDIPIGKAERLHEQGDSRLRNLKAVAEANE
KLAAAVDQVVQRGRFPLVLGGDHSIAIGTLAGVAKHYERLGVIWYDAHGDVNTAETSPSGNIHGMPLAASLGFGH
PALTQIGGYSPKIKPEHVVLIGVRSLDEGEKKFIREKGIKIYTMHEVDRLGMTRVMEETIAYLKERTDGVHLSLD
LDGLDPSDAPGVGTPVIGGLTYRESHLAMEMLAEAQIITSAEFVEVNPILDERNKTASVAVALMGSLFGEKLM*
>P1;4cevC
structureX:4cev:   2 :C: 299 :C:MOL_ID  1;  MOLECULE  ARGINASE;  CHAIN  A, B, C, D, E, F;  EC  3.5.3.1;  ENGINE:MOL_ID  1;  ORGANISM_SCIENTIFIC  BACILLUS CALDOVELOX;  STRAIN  BACILLUS SPECIES: 2.70:-1.00
KPISIIGVPMDLGQTRRGVDMGPSAMRYAGVIERLERLHYDIEDLGDIPIGKAERLHEQGDSRLRNLKAVAEANE
KLAAAVDQVVQRGRFPLVLGGDHSIAIGTLAGVAKHYERLGVIWYDAHGDVNTAETSPSGNIHGMPLAASLGFGH
PALTQIGGYSPKIKPEHVVLIGVRSLDEGEKKFIREKGIKIYTMHEVDRLGMTRVMEETIAYLKERTDGVHLSLD
LDGLDPSDAPGVGTPVIGGLTYRESHLAMEMLAEAQIITSAEFVEVNPILDERNKTASVAVALMGSLFGEKLM*
>P1;4cevD
structureX:4cev:   2 :D: 299 :D:MOL_ID  1;  MOLECULE  ARGINASE;  CHAIN  A, B, C, D, E, F;  EC  3.5.3.1;  ENGINE:MOL_ID  1;  ORGANISM_SCIENTIFIC  BACILLUS CALDOVELOX;  STRAIN  BACILLUS SPECIES: 2.70:-1.00
KPISIIGVPMDLGQTRRGVDMGPSAMRYAGVIERLERLHYDIEDLGDIPIGKAERLHEQGDSRLRNLKAVAEANE
KLAAAVDQVVQRGRFPLVLGGDHSIAIGTLAGVAKHYERLGVIWYDAHGDVNTAETSPSGNIHGMPLAASLGFGH
PALTQIGGYSPKIKPEHVVLIGVRSLDEGEKKFIREKGIKIYTMHEVDRLGMTRVMEETIAYLKERTDGVHLSLD
LDGLDPSDAPGVGTPVIGGLTYRESHLAMEMLAEAQIITSAEFVEVNPILDERNKTASVAVALMGSLFGEKLM*
>P1;4cevE
structureX:4cev:   2 :E: 299 :E:MOL_ID  1;  MOLECULE  ARGINASE;  CHAIN  A, B, C, D, E, F;  EC  3.5.3.1;  ENGINE:MOL_ID  1;  ORGANISM_SCIENTIFIC  BACILLUS CALDOVELOX;  STRAIN  BACILLUS SPECIES: 2.70:-1.00
KPISIIGVPMDLGQTRRGVDMGPSAMRYAGVIERLERLHYDIEDLGDIPIGKAERLHEQGDSRLRNLKAVAEANE
KLAAAVDQVVQRGRFPLVLGGDHSIAIGTLAGVAKHYERLGVIWYDAHGDVNTAETSPSGNIHGMPLAASLGFGH
PALTQIGGYSPKIKPEHVVLIGVRSLDEGEKKFIREKGIKIYTMHEVDRLGMTRVMEETIAYLKERTDGVHLSLD
LDGLDPSDAPGVGTPVIGGLTYRESHLAMEMLAEAQIITSAEFVEVNPILDERNKTASVAVALMGSLFGEKLM*
>P1;4cevF
structureX:4cev:   2 :F: 299 :F:MOL_ID  1;  MOLECULE  ARGINASE;  CHAIN  A, B, C, D, E, F;  EC  3.5.3.1;  ENGINE:MOL_ID  1;  ORGANISM_SCIENTIFIC  BACILLUS CALDOVELOX;  STRAIN  BACILLUS SPECIES: 2.70:-1.00
KPISIIGVPMDLGQTRRGVDMGPSAMRYAGVIERLERLHYDIEDLGDIPIGKAERLHEQGDSRLRNLKAVAEANE
KLAAAVDQVVQRGRFPLVLGGDHSIAIGTLAGVAKHYERLGVIWYDAHGDVNTAETSPSGNIHGMPLAASLGFGH
PALTQIGGYSPKIKPEHVVLIGVRSLDEGEKKFIREKGIKIYTMHEVDRLGMTRVMEETIAYLKERTDGVHLSLD
LDGLDPSDAPGVGTPVIGGLTYRESHLAMEMLAEAQIITSAEFVEVNPILDERNKTASVAVALMGSLFGEKLM*
>P1;4cpv
structureX:4cpv:   1 : : 108 : :CALCIUM-BINDING PARVALBUMIN ($P*I=4.25):CARP (CYPRINUS $CARPIO): 1.50:-1.00
AFAGVLNDADIAAALEACKAADSFNHKAFFAKVGLTSKSADDVKKAFAIIDQDKSGFIEEDELKLFLQNFKADAR
ALTDGETKTFLKAGDSDGDGKIGVDEFTALVKA*
>P1;4fiv
structureX:4fiv:   4 : : 116 : :MOL_ID  1;  MOLECULE  FELINE IMMUNODEFICIENCY VIRUS PROTEASE;  CHAIN  NULL;  SY:MOL_ID  1;  ORGANISM_SCIENTIFIC  FELINE IMMUNODEFICIENCY VIRUS;  ORGANISM_COMMO: 1.80:-1.00
VGTTTTLEKRPEILIFVNGYPIKFLLDTGADITILNRRDFQVKNSIENGRQNMIGVGGGKRGTNYINVHLEIRDE
NYKTQCIFGNVCVLEDNSLIQPLLGRDNMIKFNIRLVM*
>P1;4fgf
structureX:4fgf:  20 : : 143 : :BASIC FIBROBLAST GROWTH FACTOR ($HB/FGF$):HUMAN (HOMO $SAPIENS) EXPRESSED IN YEAST (SACCHAROMYCES  $CEREVISIAE): 1.60:-1.00
PKRLYCKNGGFFLRIHPDGRVDGVREKSDPHIKLQLQAEERGVVSIKGVCANRYLAMKEDGRLLASKCVTDECFF
FERLESNNYNTYRSRKYTSWYVALKRTGQYKLGSKTGPGQKAILFLPMS*
>P1;4dbvO
structureX:4dbv:   0 :O: 333 :O:MOL_ID  1;  MOLECULE  GLYCERALDEHYDE-3-PHOSPHATE DEHYDROGENASE;  CHAIN  O, P, Q:MOL_ID  1;  ORGANISM_SCIENTIFIC  BACILLUS STEAROTHERMOPHILUS;  CELLULAR_LOCATIO: 2.50:-1.00
AVKVGINGFGRIGRNVFRAALKNPDIEVVAVNDTGGANTLAHLLKYDSVHGRLDAEVSVNGNNLVVNGKEIIVKA
ERDPENLAWGEIGVDIVVESTGRFTKREDAAKHLEAGAKKVIISAPAKNEDITIVMGVNQDKYDPKAHHVISNAS
CTTNCLAPFAKVLHEQFGIVRGMMTTVHSYTNDQRILDASHKDLRRARAAAESIIPTTTGAAKAVALVLPELKGK
LNGMAMRVPTPNVSVVDLVAELEKEVTVEEVNAALKAAAEGELKGILAYSEEPLVSRDYNGSTVSSTIDALSTMV
IDGKMVKVVSWYDNETGYSHRVVDLAAYIASKGL*
>P1;4dbvP
structureX:4dbv:   0 :P: 333 :P:MOL_ID  1;  MOLECULE  GLYCERALDEHYDE-3-PHOSPHATE DEHYDROGENASE;  CHAIN  O, P, Q:MOL_ID  1;  ORGANISM_SCIENTIFIC  BACILLUS STEAROTHERMOPHILUS;  CELLULAR_LOCATIO: 2.50:-1.00
AVKVGINGFGRIGRNVFRAALKNPDIEVVAVNDTGGANTLAHLLKYDSVHGRLDAEVSVNGNNLVVNGKEIIVKA
ERDPENLAWGEIGVDIVVESTGRFTKREDAAKHLEAGAKKVIISAPAKNEDITIVMGVNQDKYDPKAHHVISNAS
CTTNCLAPFAKVLHEQFGIVRGMMTTVHSYTNDQRILDASHKDLRRARAAAESIIPTTTGAAKAVALVLPELKGK
LNGMAMRVPTPNVSVVDLVAELEKEVTVEEVNAALKAAAEGELKGILAYSEEPLVSRDYNGSTVSSTIDALSTMV
IDGKMVKVVSWYDNETGYSHRVVDLAAYIASKGL*
>P1;4dbvQ
structureX:4dbv:   0 :Q: 333 :Q:MOL_ID  1;  MOLECULE  GLYCERALDEHYDE-3-PHOSPHATE DEHYDROGENASE;  CHAIN  O, P, Q:MOL_ID  1;  ORGANISM_SCIENTIFIC  BACILLUS STEAROTHERMOPHILUS;  CELLULAR_LOCATIO: 2.50:-1.00
AVKVGINGFGRIGRNVFRAALKNPDIEVVAVNDTGGANTLAHLLKYDSVHGRLDAEVSVNGNNLVVNGKEIIVKA
ERDPENLAWGEIGVDIVVESTGRFTKREDAAKHLEAGAKKVIISAPAKNEDITIVMGVNQDKYDPKAHHVISNAS
CTTNCLAPFAKVLHEQFGIVRGMMTTVHSYTNDQRILDASHKDLRRARAAAESIIPTTTGAAKAVALVLPELKGK
LNGMAMRVPTPNVSVVDLVAELEKEVTVEEVNAALKAAAEGELKGILAYSEEPLVSRDYNGSTVSSTIDALSTMV
IDGKMVKVVSWYDNETGYSHRVVDLAAYIASKGL*
>P1;4dbvR
structureX:4dbv:   0 :R: 333 :R:MOL_ID  1;  MOLECULE  GLYCERALDEHYDE-3-PHOSPHATE DEHYDROGENASE;  CHAIN  O, P, Q:MOL_ID  1;  ORGANISM_SCIENTIFIC  BACILLUS STEAROTHERMOPHILUS;  CELLULAR_LOCATIO: 2.50:-1.00
AVKVGINGFGRIGRNVFRAALKNPDIEVVAVNDTGGANTLAHLLKYDSVHGRLDAEVSVNGNNLVVNGKEIIVKA
ERDPENLAWGEIGVDIVVESTGRFTKREDAAKHLEAGAKKVIISAPAKNEDITIVMGVNQDKYDPKAHHVISNAS
CTTNCLAPFAKVLHEQFGIVRGMMTTVHSYTNDQRILDASHKDLRRARAAAESIIPTTTGAAKAVALVLPELKGK
LNGMAMRVPTPNVSVVDLVAELEKEVTVEEVNAALKAAAEGELKGILAYSEEPLVSRDYNGSTVSSTIDALSTMV
IDGKMVKVVSWYDNETGYSHRVVDLAAYIASKGL*
>P1;4dpvZ
structureX:4dpv:  22 :Z: 584 :Z:MOL_ID  1;  MOLECULE  CANINE PARVOVIRUS STRAIN D VIRAL PROTEIN 2;  CHAIN  Z;  B:MOL_ID  1;  ORGANISM_SCIENTIFIC  CANINE PARVOVIRUS;  STRAIN  D;  CELL_LINE  CUL: 2.90:-1.00
GSGNGSGGGGGGGSGGVGISTGTFNNQTEFKFLENGWVEITANSSRLVHLNMPESENYRRVVVNNMDKTAVNGNM
ALDDIHAQIVTPWSLVDANAWGVWFNPGDWQLIVNTMSELHLVSFEQEIFNVVLKTVSEPPTKVYNNDLTASLMV
ALDSNNTMPFTPAAMRSETLGFYPWKPTIPTPWRYYFQWDRTLIPSHTGTSGTPTNIYHGTDPDDVQFYTIENSV
PVHLLRTGDEFATGTFFFDCKPCRLTHTWQTNRALGLPPFLNSLPQSEGATNFGDIGVQQDKRRGVTQMGNTNYI
TEATIMRPAEVGYSAPYYSFEASTQGPFKTPIAAGRGGAQTDENQAADGNPRYAFGRQHGQKTTTTGETPERFTY
IAHQDTGRYPEGDWIQNINFNLPVTNDNVLLPTDPIGGKTGINYTNIFNTYGPLTALNNVPPVYPNGQIWDKEFD
TDLKPRLHVNAPFVCQNNCPGQLFVKVAPNLTNEYDPDASANMSRIVTYSDFWWKGKLVFKAKLRASHTWNPIQQ
MSINVDNQFNYVPSNIGGMKIVYEKSQLAPRKLY*
>P1;5znf
structureN:5znf:   1 : :  30 : :ZINC-FINGER (ZFY-6T) (NMR, 13 STRUCTURES):HUMAN (HOMO SAPIENS):-1.00:-1.00
KTYQCQYCEYRSADSSNLKTHIKTKHSKEK*
>P1;5msfA
structureX:5msf:   1 :A: 129 :A:MOL_ID  1;  MOLECULE  MS2 PROTEIN CAPSID;  CHAIN  A, B, C;  ENGINEERED  YES;  M:MOL_ID  1;  ORGANISM_SCIENTIFIC  BACTERIOPHAGE MS2;  GENE  COAT PROTEIN;  EXPRE: 2.80:-1.00
ASNFTQFVLVDNGGTGDVTVAPSNFANGVAEWISSNSRSQAYKVTCSVRQSSAQNRKYTIKVEVPKVATQTVGGV
ELPVAAWRSYLNMELTIPIFATNSDCELIVKAMQGLLKDGNPIPSAIAANSGIY*
>P1;5msfB
structureX:5msf:   1 :B: 129 :B:MOL_ID  1;  MOLECULE  MS2 PROTEIN CAPSID;  CHAIN  A, B, C;  ENGINEERED  YES;  M:MOL_ID  1;  ORGANISM_SCIENTIFIC  BACTERIOPHAGE MS2;  GENE  COAT PROTEIN;  EXPRE: 2.80:-1.00
ASNFTQFVLVDNGGTGDVTVAPSNFANGVAEWISSNSRSQAYKVTCSVRQSSAQNRKYTIKVEVPKVATQTVGGV
ELPVAAWRSYLNMELTIPIFATNSDCELIVKAMQGLLKDGNPIPSAIAANSGIY*
>P1;5msfC
structureX:5msf:   1 :C: 129 :C:MOL_ID  1;  MOLECULE  MS2 PROTEIN CAPSID;  CHAIN  A, B, C;  ENGINEERED  YES;  M:MOL_ID  1;  ORGANISM_SCIENTIFIC  BACTERIOPHAGE MS2;  GENE  COAT PROTEIN;  EXPRE: 2.80:-1.00
ASNFTQFVLVDNGGTGDVTVAPSNFANGVAEWISSNSRSQAYKVTCSVRQSSAQNRKYTIKVEVPKVATQTVGGV
ELPVAAWRSYLNMELTIPIFATNSDCELIVKAMQGLLKDGNPIPSAIAANSGIY*
>P1;5cevA
structureX:5cev:   2 :A: 299 :A:MOL_ID  1;  MOLECULE  ARGINASE;  CHAIN  A, B, C, D, E, F;  EC  3.5.3.1;  ENGINE:MOL_ID  1;  ORGANISM_SCIENTIFIC  BACILLUS CALDOVELOX;  STRAIN  BACILLUS SPECIES: 2.50:-1.00
KPISIIGVPMDLGQTRRGVDMGPSAMRYAGVIERLERLHYDIEDLGDIPIGKAERLHEQGDSRLRNLKAVAEANE
KLAAAVDQVVQRGRFPLVLGGDHSIAIGTLAGVAKHYERLGVIWYDAHGDVNTAETSPSGNIHGMPLAASLGFGH
PALTQIGGYSPKIKPEHVVLIGVRSLDEGEKKFIREKGIKIYTMHEVDRLGMTRVMEETIAYLKERTDGVHLSLD
LDGLDPSDAPGVGTPVIGGLTYRESHLAMEMLAEAQIITSAEFVEVNPILDERNKTASVAVALMGSLFGEKLM*
>P1;5cevB
structureX:5cev:   2 :B: 299 :B:MOL_ID  1;  MOLECULE  ARGINASE;  CHAIN  A, B, C, D, E, F;  EC  3.5.3.1;  ENGINE:MOL_ID  1;  ORGANISM_SCIENTIFIC  BACILLUS CALDOVELOX;  STRAIN  BACILLUS SPECIES: 2.50:-1.00
KPISIIGVPMDLGQTRRGVDMGPSAMRYAGVIERLERLHYDIEDLGDIPIGKAERLHEQGDSRLRNLKAVAEANE
KLAAAVDQVVQRGRFPLVLGGDHSIAIGTLAGVAKHYERLGVIWYDAHGDVNTAETSPSGNIHGMPLAASLGFGH
PALTQIGGYSPKIKPEHVVLIGVRSLDEGEKKFIREKGIKIYTMHEVDRLGMTRVMEETIAYLKERTDGVHLSLD
LDGLDPSDAPGVGTPVIGGLTYRESHLAMEMLAEAQIITSAEFVEVNPILDERNKTASVAVALMGSLFGEKLM*
>P1;5cevC
structureX:5cev:   2 :C: 299 :C:MOL_ID  1;  MOLECULE  ARGINASE;  CHAIN  A, B, C, D, E, F;  EC  3.5.3.1;  ENGINE:MOL_ID  1;  ORGANISM_SCIENTIFIC  BACILLUS CALDOVELOX;  STRAIN  BACILLUS SPECIES: 2.50:-1.00
KPISIIGVPMDLGQTRRGVDMGPSAMRYAGVIERLERLHYDIEDLGDIPIGKAERLHEQGDSRLRNLKAVAEANE
KLAAAVDQVVQRGRFPLVLGGDHSIAIGTLAGVAKHYERLGVIWYDAHGDVNTAETSPSGNIHGMPLAASLGFGH
PALTQIGGYSPKIKPEHVVLIGVRSLDEGEKKFIREKGIKIYTMHEVDRLGMTRVMEETIAYLKERTDGVHLSLD
LDGLDPSDAPGVGTPVIGGLTYRESHLAMEMLAEAQIITSAEFVEVNPILDERNKTASVAVALMGSLFGEKLM*
>P1;5cevD
structureX:5cev:   2 :D: 299 :D:MOL_ID  1;  MOLECULE  ARGINASE;  CHAIN  A, B, C, D, E, F;  EC  3.5.3.1;  ENGINE:MOL_ID  1;  ORGANISM_SCIENTIFIC  BACILLUS CALDOVELOX;  STRAIN  BACILLUS SPECIES: 2.50:-1.00
KPISIIGVPMDLGQTRRGVDMGPSAMRYAGVIERLERLHYDIEDLGDIPIGKAERLHEQGDSRLRNLKAVAEANE
KLAAAVDQVVQRGRFPLVLGGDHSIAIGTLAGVAKHYERLGVIWYDAHGDVNTAETSPSGNIHGMPLAASLGFGH
PALTQIGGYSPKIKPEHVVLIGVRSLDEGEKKFIREKGIKIYTMHEVDRLGMTRVMEETIAYLKERTDGVHLSLD
LDGLDPSDAPGVGTPVIGGLTYRESHLAMEMLAEAQIITSAEFVEVNPILDERNKTASVAVALMGSLFGEKLM*
>P1;5cevE
structureX:5cev:   2 :E: 299 :E:MOL_ID  1;  MOLECULE  ARGINASE;  CHAIN  A, B, C, D, E, F;  EC  3.5.3.1;  ENGINE:MOL_ID  1;  ORGANISM_SCIENTIFIC  BACILLUS CALDOVELOX;  STRAIN  BACILLUS SPECIES: 2.50:-1.00
KPISIIGVPMDLGQTRRGVDMGPSAMRYAGVIERLERLHYDIEDLGDIPIGKAERLHEQGDSRLRNLKAVAEANE
KLAAAVDQVVQRGRFPLVLGGDHSIAIGTLAGVAKHYERLGVIWYDAHGDVNTAETSPSGNIHGMPLAASLGFGH
PALTQIGGYSPKIKPEHVVLIGVRSLDEGEKKFIREKGIKIYTMHEVDRLGMTRVMEETIAYLKERTDGVHLSLD
LDGLDPSDAPGVGTPVIGGLTYRESHLAMEMLAEAQIITSAEFVEVNPILDERNKTASVAVALMGSLFGEKLM*
>P1;5cevF
structureX:5cev:   2 :F: 299 :F:MOL_ID  1;  MOLECULE  ARGINASE;  CHAIN  A, B, C, D, E, F;  EC  3.5.3.1;  ENGINE:MOL_ID  1;  ORGANISM_SCIENTIFIC  BACILLUS CALDOVELOX;  STRAIN  BACILLUS SPECIES: 2.50:-1.00
KPISIIGVPMDLGQTRRGVDMGPSAMRYAGVIERLERLHYDIEDLGDIPIGKAERLHEQGDSRLRNLKAVAEANE
KLAAAVDQVVQRGRFPLVLGGDHSIAIGTLAGVAKHYERLGVIWYDAHGDVNTAETSPSGNIHGMPLAASLGFGH
PALTQIGGYSPKIKPEHVVLIGVRSLDEGEKKFIREKGIKIYTMHEVDRLGMTRVMEETIAYLKERTDGVHLSLD
LDGLDPSDAPGVGTPVIGGLTYRESHLAMEMLAEAQIITSAEFVEVNPILDERNKTASVAVALMGSLFGEKLM*
>P1;5cpv
structureX:5cpv:   1 : : 108 : :CALCIUM-BINDING PARVALBUMIN B:CARP (CYPRINUS $CARPIO): 1.60:-1.00
AFAGVLNDADIAAALEACKAADSFNHKAFFAKVGLTSKSADDVKKAFAIIDQDKSGFIEEDELKLFLQNFKADAR
ALTDGETKTFLKAGDSDGDGKIGVDEFTALVKA*
>P1;5fiv
structureX:5fiv:   5 : : 116 : :MOL_ID  1;  MOLECULE  PROTEASE;  CHAIN  NULL;  EC  3.4.23.16;  ENGINEERED  YES:MOL_ID  1;  ORGANISM_SCIENTIFIC  FELINE IMMUNODEFICIENCY VIRUS  (ISOLATE PETALU: 1.90:-1.00
GTTTTLEKRPEILIFVNGYPIKFLLDTGADITILNRRDFQVKNSIENGRQNMIGIGGGKRGTNYINVHLEIRDEN
YKTQCIFGNVCVLEDNSLIQPLLGRDNMIKFNIRLVM*
>P1;6msfA
structureX:6msf:   1 :A: 129 :A:MOL_ID  1;  MOLECULE  MS2 PROTEIN CAPSID;  CHAIN  A, B, C;  ENGINEERED  YES;  M:MOL_ID  1;  ORGANISM_SCIENTIFIC  BACTERIOPHAGE MS2;  GENE  COAT PROTEIN;  EXPRE: 2.80:-1.00
ASNFTQFVLVDNGGTGDVTVAPSNFANGVAEWISSNSRSQAYKVTCSVRQSSAQNRKYTIKVEVPKVATQTVGGV
ELPVAAWRSYLNMELTIPIFATNSDCELIVKAMQGLLKDGNPIPSAIAANSGIY*
>P1;6msfB
structureX:6msf:   1 :B: 129 :B:MOL_ID  1;  MOLECULE  MS2 PROTEIN CAPSID;  CHAIN  A, B, C;  ENGINEERED  YES;  M:MOL_ID  1;  ORGANISM_SCIENTIFIC  BACTERIOPHAGE MS2;  GENE  COAT PROTEIN;  EXPRE: 2.80:-1.00
ASNFTQFVLVDNGGTGDVTVAPSNFANGVAEWISSNSRSQAYKVTCSVRQSSAQNRKYTIKVEVPKVATQTVGGV
ELPVAAWRSYLNMELTIPIFATNSDCELIVKAMQGLLKDGNPIPSAIAANSGIY*
>P1;6msfC
structureX:6msf:   1 :C: 129 :C:MOL_ID  1;  MOLECULE  MS2 PROTEIN CAPSID;  CHAIN  A, B, C;  ENGINEERED  YES;  M:MOL_ID  1;  ORGANISM_SCIENTIFIC  BACTERIOPHAGE MS2;  GENE  COAT PROTEIN;  EXPRE: 2.80:-1.00
ASNFTQFVLVDNGGTGDVTVAPSNFANGVAEWISSNSRSQAYKVTCSVRQSSAQNRKYTIKVEVPKVATQTVGGV
ELPVAAWRSYLNMELTIPIFATNSDCELIVKAMQGLLKDGNPIPSAIAANSGIY*
>P1;6fiv
structureX:6fiv:   5 : : 116 : :MOL_ID  1;  MOLECULE  PROTEASE;  CHAIN  NULL;  EC  3.4.23.16;  ENGINEERED  YES:MOL_ID  1;  ORGANISM_SCIENTIFIC  FELINE IMMUNODEFICIENCY VIRUS  (ISOLATE PETALU: 1.90:-1.00
GTTTTLEKRPEILIFVNGYPIKFLLDTGADITILNRRDFQVKNSIENGRQNMIGVGGGKRGTNYINVHLEIRDEN
YKTQCIFGNVCVLEDNSLIVPLLGRDNMIKFNIRLVM*
>P1;6gsvA
structureX:6gsv:   1 :A: 217 :A:MOL_ID  1;  MOLECULE  MU CLASS GLUTATHIONE S-TRANSFERASE OF ISOENZYME  3-3;  CH:MOL_ID  1;  ORGANISM_SCIENTIFIC  RATTUS RATTUS;  ORGANISM_COMMON  RAT;  ORGAN: 1.75:-1.00
PMILGYWNVRGLSHPIRLLLEYTDSSYEEKRYAMGDAPDYDRSQWLNEKFKLGLDFPNLPYLIDGSRKITQSNAI
MRYLARKHHLCGETEEERIRADIVENQVMDNRMQLIMLCYNPDFEKQKPEFLKTIPEKMKLYSEFLGKRPWFAGD
KVTYVDFLAYDILDQYHIFEPKCLDAFPNLKDFLARFEGLKKISAYMKSSRYLSTPIFSKLAQWSNK*
>P1;6gsvB
structureX:6gsv:   1 :B: 217 :B:MOL_ID  1;  MOLECULE  MU CLASS GLUTATHIONE S-TRANSFERASE OF ISOENZYME  3-3;  CH:MOL_ID  1;  ORGANISM_SCIENTIFIC  RATTUS RATTUS;  ORGANISM_COMMON  RAT;  ORGAN: 1.75:-1.00
PMILGYWNVRGLSHPIRLLLEYTDSSYEEKRYAMGDAPDYDRSQWLNEKFKLGLDFPNLPYLIDGSRKITQSNAI
MRYLARKHHLCGETEEERIRADIVENQVMDNRMQLIMLCYNPDFEKQKPEFLKTIPEKMKLYSEFLGKRPWFAGD
KVTYVDFLAYDILDQYHIFEPKCLDAFPNLKDFLARFEGLKKISAYMKSSRYLSTPIFSKLAQWSNK*
>P1;7znf
structureN:7znf:   1 : :  30 : :ZINC-FINGER (ZFY-SWAP) (NMR, 12 STRUCTURES):HUMAN (HOMO SAPIENS):-1.00:-1.00
KTYQCQYCEKRFADSSNLKTHIKTKHSKEK*
>P1;7icfA
structureX:7icf:   9 :A: 335 :A:MOL_ID  1;  MOLECULE  DNA POLYMERASE BETA;  CHAIN  A;  EC  2.7.7.7;  ENGINEERED:MOL_ID  1;  ORGANISM_SCIENTIFIC  HOMO SAPIENS;  ORGANISM_COMMON  HUMAN;  EXPRES: 3.10:-1.00
ETLNGGITDMLTELANFEKNVSQAIHKYNAYRKAASVIAKYPHKIKSGAEAKKLPGVGTKIAEKIDEFLATGKLR
KLEKIRQDDTSSSINFLTRVSGIGPSAARKFVDEGIKTLEDLRKNEDKLNHHQRIGLKYFGDFEKRIPREEMLQM
QDIVLNEVKKVDSEYIATVCGSFRRGAESSGDMDVLLTHPSFTSESTKQPKLLHQVVEQLQKVHFITDTLSKGET
KFMGVCQLPSKNDEKEYPHRRIDIRLIPKDQYYCGVLYFTGSDIFNKNMRAHALEKGFTINEYTIRPLGVTGVAG
EPLPVDSEKDIFDYIQWKYREPKDRSE*
>P1;7icvA
structureX:7icv:   9 :A: 335 :A:MOL_ID  1;  MOLECULE  DNA POLYMERASE BETA;  CHAIN  A;  EC  2.7.7.7;  ENGINEERED:MOL_ID  1;  ORGANISM_SCIENTIFIC  HOMO SAPIENS;  ORGANISM_COMMON  HUMAN;  EXPRES: 2.80:-1.00
ETLNGGITDMLTELANFEKNVSQAIHKYNAYRKAASVIAKYPHKIKSGAEAKKLPGVGTKIAEKIDEFLATGKLR
KLEKIRQDDTSSSINFLTRVSGIGPSAARKFVDEGIKTLEDLRKNEDKLNHHQRIGLKYFGDFEKRIPREEMLQM
QDIVLNEVKKVDSEYIATVCGSFRRGAESSGDMDVLLTHPSFTSESTKQPKLLHQVVEQLQKVHFITDTLSKGET
KFMGVCQLPSKNDEKEYPHRRIDIRLIPKDQYYCGVLYFTGSDIFNKNMRAHALEKGFTINEYTIRPLGVTGVAG
EPLPVDSEKDIFDYIQWKYREPKDRSE*
>P1;7msfA
structureX:7msf:   1 :A: 129 :A:MOL_ID  1;  MOLECULE  MS2 PROTEIN CAPSID;  CHAIN  A, B, C;  ENGINEERED  YES;  M:MOL_ID  1;  ORGANISM_SCIENTIFIC  BACTERIOPHAGE MS2;  GENE  COAT PROTEIN;  EXPRE: 2.80:-1.00
ASNFTQFVLVDNGGTGDVTVAPSNFANGVAEWISSNSRSQAYKVTCSVRQSSAQNRKYTIKVEVPKVATQTVGGV
ELPVAAWRSYLNMELTIPIFATNSDCELIVKAMQGLLKDGNPIPSAIAANSGIY*
>P1;7msfB
structureX:7msf:   1 :B: 129 :B:MOL_ID  1;  MOLECULE  MS2 PROTEIN CAPSID;  CHAIN  A, B, C;  ENGINEERED  YES;  M:MOL_ID  1;  ORGANISM_SCIENTIFIC  BACTERIOPHAGE MS2;  GENE  COAT PROTEIN;  EXPRE: 2.80:-1.00
ASNFTQFVLVDNGGTGDVTVAPSNFANGVAEWISSNSRSQAYKVTCSVRQSSAQNRKYTIKVEVPKVATQTVGGV
ELPVAAWRSYLNMELTIPIFATNSDCELIVKAMQGLLKDGNPIPSAIAANSGIY*
>P1;7msfC
structureX:7msf:   1 :C: 129 :C:MOL_ID  1;  MOLECULE  MS2 PROTEIN CAPSID;  CHAIN  A, B, C;  ENGINEERED  YES;  M:MOL_ID  1;  ORGANISM_SCIENTIFIC  BACTERIOPHAGE MS2;  GENE  COAT PROTEIN;  EXPRE: 2.80:-1.00
ASNFTQFVLVDNGGTGDVTVAPSNFANGVAEWISSNSRSQAYKVTCSVRQSSAQNRKYTIKVEVPKVATQTVGGV
ELPVAAWRSYLNMELTIPIFATNSDCELIVKAMQGLLKDGNPIPSAIAANSGIY*
>P1;1zqfA
structureX:1zqf:   9 :A: 335 :A:MOL_ID  1;  MOLECULE  DNA POLYMERASE BETA;  CHAIN  A;  EC  2.7.7.7;  ENGINEERED:MOL_ID  1;  ORGANISM_SCIENTIFIC  HOMO SAPIENS;  ORGANISM_COMMON  HUMAN;  EXPRES: 2.90:-1.00
ETLNGGITDMLTELANFEKNVSQAIHKYNAYRKAASVIAKYPHKIKSGAEAKKLPGVGTKIAEKIDEFLATGKLR
KLEKIRQDDTSSSINFLTRVSGIGPSAARKFVDEGIKTLEDLRKNEDKLNHHQRIGLKYFGDFEKRIPREEMLQM
QDIVLNEVKKVDSEYIATVCGSFRRGAESSGDMDVLLTHPSFTSESTKQPKLLHQVVEQLQKVHFITDTLSKGET
KFMGVCQLPSKNDEKEYPHRRIDIRLIPKDQYYCGVLYFTGSDIFNKNMRAHALEKGFTINEYTIRPLGVTGVAG
EPLPVDSEKDIFDYIQWKYREPKDRSE*
>P1;1zqv
structureX:1zqv:  91 : : 335 : :MOL_ID  1;  MOLECULE  DNA POLYMERASE BETA;  CHAIN  NULL;  FRAGMENT  C-TERMINAL:MOL_ID  1;  ORGANISM_SCIENTIFIC  RATTUS NORVEGICUS;  ORGANISM_COMMON  RAT;  EXP: 2.70:-1.00
DDTSSSINFLTRVTGIGPSAARKLVDEGIKTLEDLRKNEDKLNHHQRIGLKYFEDFEKRIPREEMLQMQDIVLNE
VKKLDPEYIATVCGSFRRGAESSGDMDVLLTHPNFTSESSKQPKLLHRVVEQLQKVRFITDTLSKGETKFMGVCQ
LPSENEYPHRRIDIRLIPKDQYYCGVLYFTGSDIFNKNMRAHALEKGFTINEYTIRPLGVTGVAGEPLPVDSEQD
IFDYIQWRYREPKDRSE*
>P1;1zwf
structureN:1zwf:   2 : :  35 : :MOL_ID  1;  MOLECULE  PARATHYROID HORMONE;  CHAIN  NULL;  FRAGMENT  4 - 37;  SY:MOL_ID  1;  SYNTHETIC  YES:-1.00:-1.00
EIQLMHNLGKHLNSMERVEWLRKKLQDVHNFVAL*
>P1;1xif
structureX:1xif:   1 : : 388 : :D-XYLOSE ISOMERASE (E.C.5.3.1.5) COMPLEXED WITH GLUCOSE,  MN, AND MG (PH 8.0):(STREPTOMYCES RUBIGINOSUS): 1.60:-1.00
MNYQPTPEDRFTFGLWTVGWQGRDPFGDATRRALDPVESVQRLAELGAHGVTFHDDDLIPFGSSDSEREEHVKRF
RQALDDTGMKVPMATTNLFTHPVFKDGGFTANDRDVRRYALRKTIRNIDLAVELGAETYVAWGGREGAESGGAKD
VRDALDRMKEAFDLLGEYVTSQGYDIRFAIEPKPNEPRGDILLPTVGHALAFIERLERPELYGVNPEVGHEQMAG
LNFPHGIAQALWAGKLFHIDLNGQNGIKYDQDLRFGAGDLRAAFWLVDLLESAGYSGPRHFDFKPPRTEDFDGVW
ASAAGCMRNYLILKERAAAFRADPEVQEALRASRLDELARPTAADGLQALLDDRSAFEEFDVDAAAARGMAFERL
DQLAMDHLLGARG*
>P1;1xlfA
structureX:1xlf:   2 :A: 394 :A:D-*XYLOSE ISOMERASE (E.C.5.3.1.5) COMPLEX WITH GLUCONATE  AND MANGANESE:(ARTHROBACTER, STRAIN B3728): 2.50:-1.00
VQPTPADHFTFGLWTVGWTGADPFGVATRKNLDPVEAVHKLAELGAYGITFHDNDLIPFDATEAEREKILGDFNQ
ALKDTGLKVPMVTTNLFSHPVFKDGGFTSNDRSIRRFALAKVLHNIDLAAEMGAETFVMWGGREGSEYDGSKDLA
AALDRMREGVDTAAGYIKDKGYNLRIALEPKPNEPRGDIFLPTVGHGLAFIEQLEHGDIVGLNPETGHEQMAGLN
FTHGIAQALWAEKLFHIDLNGQRGIKYDQDLVFGHGDLTSAFFTVDLLENGFPNGGPKYTGPRHFDYKPSRTDGY
DGVWDSAKANMSMYLLLKERALAFRADPEVQEAMKTSGVFELGETTLNAGESAADLMNDSASFAGFDAEAAAERN
FAFIRLNQLAIEHLLGSR*
>P1;1xlfB
structureX:1xlf:   2 :B: 394 :B:D-*XYLOSE ISOMERASE (E.C.5.3.1.5) COMPLEX WITH GLUCONATE  AND MANGANESE:(ARTHROBACTER, STRAIN B3728): 2.50:-1.00
VQPTPADHFTFGLWTVGWTGADPFGVATRKNLDPVEAVHKLAELGAYGITFHDNDLIPFDATEAEREKILGDFNQ
ALKDTGLKVPMVTTNLFSHPVFKDGGFTSNDRSIRRFALAKVLHNIDLAAEMGAETFVMWGGREGSEYDGSKDLA
AALDRMREGVDTAAGYIKDKGYNLRIALEPKPNEPRGDIFLPTVGHGLAFIEQLEHGDIVGLNPETGHEQMAGLN
FTHGIAQALWAEKLFHIDLNGQRGIKYDQDLVFGHGDLTSAFFTVDLLENGFPNGGPKYTGPRHFDYKPSRTDGY
DGVWDSAKANMSMYLLLKERALAFRADPEVQEAMKTSGVFELGETTLNAGESAADLMNDSASFAGFDAEAAAERN
FAFIRLNQLAIEHLLGSR*
>P1;1xzf
structureX:1xzf:  17 : : 213 : :MOL_ID  1;  MOLECULE  CUTINASE;  CHAIN  NULL;  EC  3.1.1.-;  ENGINEERED  YES;:MOL_ID  1;  ORGANISM_SCIENTIFIC  FUSARIUM SOLANI PISI;  EXPRESSION_SYSTEM  SACC: 1.69:-1.00
RTTRDDLINGNSASCADVIFIYARGSTETGNLGTLGPSIASNLESAFGKDGVWIQGVGGAYRATLGDNALPRGTS
SAAIREMLGLFQQANTKCPDATLIAGGYSQGAALAAASIEDLDSAIRDKIAGCVLFGYTKNLQNRGRIPNYPADR
TKVFCNTGDLVCTGSLIVAAPHLAYGPDARGPAPEFLIEKVRAVRGS*
>P1;1xuf
structureX:1xuf:  16 : : 245 : :MOL_ID  1;  MOLECULE  TRYPSIN;  CHAIN  NULL;  EC  3.4.21.4;  OTHER_DETAILS  TRY:MOL_ID  1;  ORGANISM_SCIENTIFIC  BOS TAURUS;  ORGANISM_COMMON  BOVINE: 2.04:-1.00
IVGGYTCGANTVPYQVSLNSGYHFCGGSLINSQWVVSAAHCYKSGIQVRLGEDNINVVEGNEQFISASKSIVHPS
YNSNTLNNDIMLIKLKSAASLNSRVASISLPTSCASAGTQCLISGWGNTKSSGTSYPDVLKCLKAPILSDSSCKS
AYPGQITSNMFCAGYLEGGKDSCQGDSGGPVVCSGKLQGIVSWGSGCAQKNKPGVYTKVCNYVSWIKQTIASN*
>P1;1ykfA
structureX:1ykf:   1 :A: 352 :A:MOL_ID  1;  MOLECULE  NADP-DEPENDENT ALCOHOL DEHYDROGENASE;  CHAIN  A, B, C, D;:MOL_ID  1;  ORGANISM_SCIENTIFIC  THERMOANAEROBIUM BROCKII;  EXPRESSION_SYSTEM: 2.50:-1.00
MKGFAMLSIGKVGWIEKEKPAPGPFDAIVRPLAVAPCTSDIHTVFEGAIGERHNMILGHEAVGEVVEVGSEVKDF
KPGDRVVVPAITPDWRTSEVQRGYHQHSGGMLAGWKFSNVKDGVFGEFFHVNDADMNLAHLPKEIPLEAAVMIPD
MMTTGFHGAELADIELGATVAVLGIGPVGLMAVAGAKLRGAGRIIAVGSRPVCVDAAKYYGATDIVNYKDGPIES
QIMNLTEGKGVDAAIIAGGNADIMATAVKIVKPGGTIANVNYFGEGEVLPVPRLEWGCGMAHKTIKGGLCPGGRL
RMERLIDLVFYKRVDPSKLVTHVFRGFDNIEKAFMLMKDKPKDLIKPVVILA*
>P1;1ykfB
structureX:1ykf:   1 :B: 352 :B:MOL_ID  1;  MOLECULE  NADP-DEPENDENT ALCOHOL DEHYDROGENASE;  CHAIN  A, B, C, D;:MOL_ID  1;  ORGANISM_SCIENTIFIC  THERMOANAEROBIUM BROCKII;  EXPRESSION_SYSTEM: 2.50:-1.00
MKGFAMLSIGKVGWIEKEKPAPGPFDAIVRPLAVAPCTSDIHTVFEGAIGERHNMILGHEAVGEVVEVGSEVKDF
KPGDRVVVPAITPDWRTSEVQRGYHQHSGGMLAGWKFSNVKDGVFGEFFHVNDADMNLAHLPKEIPLEAAVMIPD
MMTTGFHGAELADIELGATVAVLGIGPVGLMAVAGAKLRGAGRIIAVGSRPVCVDAAKYYGATDIVNYKDGPIES
QIMNLTEGKGVDAAIIAGGNADIMATAVKIVKPGGTIANVNYFGEGEVLPVPRLEWGCGMAHKTIKGGLCPGGRL
RMERLIDLVFYKRVDPSKLVTHVFRGFDNIEKAFMLMKDKPKDLIKPVVILA*
>P1;1ykfC
structureX:1ykf:   1 :C: 352 :C:MOL_ID  1;  MOLECULE  NADP-DEPENDENT ALCOHOL DEHYDROGENASE;  CHAIN  A, B, C, D;:MOL_ID  1;  ORGANISM_SCIENTIFIC  THERMOANAEROBIUM BROCKII;  EXPRESSION_SYSTEM: 2.50:-1.00
MKGFAMLSIGKVGWIEKEKPAPGPFDAIVRPLAVAPCTSDIHTVFEGAIGERHNMILGHEAVGEVVEVGSEVKDF
KPGDRVVVPAITPDWRTSEVQRGYHQHSGGMLAGWKFSNVKDGVFGEFFHVNDADMNLAHLPKEIPLEAAVMIPD
MMTTGFHGAELADIELGATVAVLGIGPVGLMAVAGAKLRGAGRIIAVGSRPVCVDAAKYYGATDIVNYKDGPIES
QIMNLTEGKGVDAAIIAGGNADIMATAVKIVKPGGTIANVNYFGEGEVLPVPRLEWGCGMAHKTIKGGLCPGGRL
RMERLIDLVFYKRVDPSKLVTHVFRGFDNIEKAFMLMKDKPKDLIKPVVILA*
>P1;1ykfD
structureX:1ykf:   1 :D: 352 :D:MOL_ID  1;  MOLECULE  NADP-DEPENDENT ALCOHOL DEHYDROGENASE;  CHAIN  A, B, C, D;:MOL_ID  1;  ORGANISM_SCIENTIFIC  THERMOANAEROBIUM BROCKII;  EXPRESSION_SYSTEM: 2.50:-1.00
MKGFAMLSIGKVGWIEKEKPAPGPFDAIVRPLAVAPCTSDIHTVFEGAIGERHNMILGHEAVGEVVEVGSEVKDF
KPGDRVVVPAITPDWRTSEVQRGYHQHSGGMLAGWKFSNVKDGVFGEFFHVNDADMNLAHLPKEIPLEAAVMIPD
MMTTGFHGAELADIELGATVAVLGIGPVGLMAVAGAKLRGAGRIIAVGSRPVCVDAAKYYGATDIVNYKDGPIES
QIMNLTEGKGVDAAIIAGGNADIMATAVKIVKPGGTIANVNYFGEGEVLPVPRLEWGCGMAHKTIKGGLCPGGRL
RMERLIDLVFYKRVDPSKLVTHVFRGFDNIEKAFMLMKDKPKDLIKPVVILA*
>P1;1ymv
structureX:1ymv:   6 : : 129 : :MOL_ID  1;  MOLECULE  CHEY;  CHAIN  NULL;  ENGINEERED  YES;  MUTATION  INS(M0),:MOL_ID  1;  ORGANISM_SCIENTIFIC  ESCHERICHIA COLI;  EXPRESSION_SYSTEM  ESCHERIC: 1.90:-1.00
LKFLVVDDGGTGRRIVRNLLKELGFNNVEEAEDGVDALNKLQAGGYGFVISDWNMPNMDGLELLKTIRADGAMSA
LPVLMVTAEAKKENIIAAAQAGASGYVVKPFTAATLEEKLNKIFEKLGM*
>P1;1ybvA
structureX:1ybv:  14 :A: 283 :A:MOL_ID  1;  MOLECULE  TRIHYDROXYNAPHTHALENE REDUCTASE;  CHAIN  A, B;  SYNONYM:MOL_ID  1;  ORGANISM_SCIENTIFIC  MAGNAPORTHE GRISEA;  ORGANISM_COMMON  RICE BLA: 2.80:-1.00
DAIPGPLGPQSASLEGKVALVTGAGRGIGREMAMELGRRGCKVIVNYANSTESAEEVVAAIKKNGSDAACVKANV
GVVEDIVRMFEEAVKIFGKLDIVCSNSGVVSFGHVKDVTPEEFDRVFTINTRGQFFVAREAYKHLEIGGRLILMG
SITGQAKAVPKHAVYSGSKGAIETFARCMAIDMADKKITVNVVAPGGIKTDMYHAVCREYIPNGENLSNEEVDEY
AAVQWSPLRRVGLPIDIARVVCFLASNDGGWVTGKVIGIDGGACM*
>P1;1ybvB
structureX:1ybv:  14 :B: 283 :B:MOL_ID  1;  MOLECULE  TRIHYDROXYNAPHTHALENE REDUCTASE;  CHAIN  A, B;  SYNONYM:MOL_ID  1;  ORGANISM_SCIENTIFIC  MAGNAPORTHE GRISEA;  ORGANISM_COMMON  RICE BLA: 2.80:-1.00
DAIPGPLGPQSASLEGKVALVTGAGRGIGREMAMELGRRGCKVIVNYANSTESAEEVVAAIKKNGSDAACVKANV
GVVEDIVRMFEEAVKIFGKLDIVCSNSGVVSFGHVKDVTPEEFDRVFTINTRGQFFVAREAYKHLEIGGRLILMG
SITGQAKAVPKHAVYSGSKGAIETFARCMAIDMADKKITVNVVAPGGIKTDMYHAVCREYIPNGENLSNEEVDEY
AAVQWSPLRRVGLPIDIARVVCFLASNDGGWVTGKVIGIDGGACM*
>P1;1ydvA
structureX:1ydv:   3 :A: 248 :A:MOL_ID  1;  MOLECULE  TRIOSEPHOSPHATE ISOMERASE;  CHAIN  A, B;  SYNONYM  TIM;:MOL_ID  1;  ORGANISM_SCIENTIFIC  PLASMODIUM FALCIPARUM;  EXPRESSION_SYSTEM  ESC: 2.20:-1.00
RKYFVAANWKCNGTLESIKSLTNSFNNLDFDPSKLDVVVFPVSVHYDHTRKLLQSKFSTGIQNVSKFGNGSYTGE
VSAEIAKDLNIEYVIIGHFERRKYFHETDEDVREKLQASLKNNLKAVVCFGESLEQREQNKTIEVITKQVKAFVD
LIDNFDNVILVYEPLWAIGTGKTATPEQAQLVHKEIRKIVKDTCGEKQANQIRILYGGSVNTENCSSLIQQEDID
GFLVGNASLKESFVDIIKSAM*
>P1;1ydvB
structureX:1ydv:   3 :B: 248 :B:MOL_ID  1;  MOLECULE  TRIOSEPHOSPHATE ISOMERASE;  CHAIN  A, B;  SYNONYM  TIM;:MOL_ID  1;  ORGANISM_SCIENTIFIC  PLASMODIUM FALCIPARUM;  EXPRESSION_SYSTEM  ESC: 2.20:-1.00
RKYFVAANWKCNGTLESIKSLTNSFNNLDFDPSKLDVVVFPVSVHYDHTRKLLQSKFSTGIQNVSKFGNGSYTGE
VSAEIAKDLNIEYVIIGHFERRKYFHETDEDVREKLQASLKNNLKAVVCFGESLEQREQNKTIEVITKQVKAFVD
LIDNFDNVILVYEPLWAIGTGKTATPEQAQLVHKEIRKIVKDTCGEKQANQIRILYGGSVNTENCSSLIQQEDID
GFLVGNASLKESFVDIIKSAM*
>P1;1yefL
structureX:1yef:   1 :L: 214 :L:MOL_ID  1;  MOLECULE  IGG2A FAB FRAGMENT;  CHAIN  L, H;  OTHER_DETAILS  STRUCTU:MOL_ID  1;  ORGANISM_SCIENTIFIC  MUS MUSCULUS;  ORGANISM_COMMON  MOUSE: 2.00:-1.00
DIVMTQSPLTLSVTIGQPASISCKSSQSLLYSNGKTYLNWLLQRPGQSPKRLIHLVSKLDSGVPDRITGSGSGTD
FTLKISRVEAADLGVYYCVQGTHFPYTFGGGTKLEILRGDAAPTVSIFPPSSEQLTSGGASVVCFLNNFYPKDIN
VKWKIDGSERQNGVLNSWTDQDSKDSTYSMSSTLTLTKDEYERHNSYTCEATHKTSTSPIVKSFNRNEC*
>P1;1yefH
structureX:1yef:   1 :H: 223 :H:MOL_ID  1;  MOLECULE  IGG2A FAB FRAGMENT;  CHAIN  L, H;  OTHER_DETAILS  STRUCTU:MOL_ID  1;  ORGANISM_SCIENTIFIC  MUS MUSCULUS;  ORGANISM_COMMON  MOUSE: 2.00:-1.00
EMQLQQSGAELLRPGTSVKLSCKTSGYIFTSYWIHWVKQRSGQGLEWIARIYPGTGSTYYNEKFKGKATLTADKS
SSTAYMQLSTLKSEDSAVYFCTRWGFIPVREDYVMDYWGQGTLVTVSSAKTTAPSVYPLAPVCGDTTGSSVTLGC
LVKGYFPEPVTLTWNSGSLSSGVHTFPAVLQSDLYTLSSSVTVTSSTWPSQSITCNVAHPASSTKVDKKIEP*
>P1;1ytfA
structureX:1ytf:  61 :A: 240 :A:MOL_ID  1;  MOLECULE  YEAST TATA-BOX BINDING PROTEIN;  CHAIN  A;  FRAGMENT  C-T:MOL_ID  1;  ORGANISM_SCIENTIFIC  SACCHAROMYCES CEREVISIAE;  ORGANISM_COMMON  BA: 2.50:-1.00
SGIVPTLQNIVATVTLGCRLDLKTVALHARNAEYNPKRFAAVIMRIREPKTTALIFASGKMVVTGAKSEDDSKLA
SRKYARIIQKIGFAAKFTDFKIQNIVGSCDVKFPIRLEGLAFSHGTFSSYEPELFPGLIYRMVKPKIVLLIFVSG
KIVLTGAKQREEIYQAFEAIYPVLSEFRKM*
>P1;1ytfB
structureX:1ytf:   2 :B:  47 :B:MOL_ID  1;  MOLECULE  YEAST TATA-BOX BINDING PROTEIN;  CHAIN  A;  FRAGMENT  C-T:MOL_ID  1;  ORGANISM_SCIENTIFIC  SACCHAROMYCES CEREVISIAE;  ORGANISM_COMMON  BA: 2.50:-1.00
SNAEASRVYEIIVESVVNEVREDFENAGIDEQTLQDLKNIWQKKLT*
>P1;1ytfC
structureX:1ytf: 241 :C: 286 :C:MOL_ID  1;  MOLECULE  YEAST TATA-BOX BINDING PROTEIN;  CHAIN  A;  FRAGMENT  C-T:MOL_ID  1;  ORGANISM_SCIENTIFIC  SACCHAROMYCES CEREVISIAE;  ORGANISM_COMMON  BA: 2.50:-1.00
ENLMLCLYDKVTRTKARWKCSLKDGVVTINRNDYTFQKAQVEAEWV*
>P1;1ytfD
structureX:1ytf:   5 :D: 119 :D:MOL_ID  1;  MOLECULE  YEAST TATA-BOX BINDING PROTEIN;  CHAIN  A;  FRAGMENT  C-T:MOL_ID  1;  ORGANISM_SCIENTIFIC  SACCHAROMYCES CEREVISIAE;  ORGANISM_COMMON  BA: 2.50:-1.00
GYYELYRRSTIGNSLVDALDTLISDGRIEASLAMRVLETFDKVVAETLKDNTQSKLTVKGNLDTYGFCDDVWTFI
VKNCQVTVESVISVDKLRIVACNSK*
>P1;1yuf
structureN:1yuf:   1 : :  50 : :MOL_ID  1;  MOLECULE  TRANSFORMING GROWTH FACTOR ALPHA;  CHAIN  NULL;  SYNONYM:MOL_ID  1;  ORGANISM_SCIENTIFIC  HOMO SAPIENS;  ORGANISM_COMMON  HUMAN;  EXPRES:-1.00:-1.00
VVSHFNDCPDSHTQFCFHGTCRFLVQEDKPACVCHSGYVGARCEHADLLA*
>P1;1rlf
structureN:1rlf: 646 : : 735 : :MOL_ID  1;  MOLECULE  RLF;  CHAIN  NULL;  FRAGMENT  RAS BINDING DOMAIN, RESIDUE:MOL_ID  1;  ORGANISM_SCIENTIFIC  MUS MUSCULUS;  ORGANISM_COMMON  MOUSE;  EXPRES:-1.00:-1.00
GSSDCRIIRVQMELGEDGSVYKSILVTSQDKAPSVISRVLKKNNRDSAVASEFELVQLLPGDRELTIPHSANVFY
AMDGASHDFLLRQRR*
>P1;1rl6A
structureX:1rl6:   7 :A: 170 :A:MOL_ID  1;  MOLECULE  RIBOSOMAL PROTEIN L6;  CHAIN  A;  ENGINEERED  YES;  BIOLO:MOL_ID  1;  ORGANISM_SCIENTIFIC  BACILLUS STEAROTHERMOPHILUS;  CELLULAR_LOCATIO: 2.00:-1.00
PIEIPAGVTVTVNGNTVTVKGPKGELTRTFHPDMTITVEGNVITVTRPSDEKHHRALHGTTRSLLANMVEGVSKG
YEKALELVGVGYRASKQGKKLVLSVGYSHPVEIEPEEGLEIEVPSQTKIIVKGADKQRVGELAANIRAVRPPEPY
KGKGIRYEGELVRL*
>P1;1rmfL
structureX:1rmf:   1 :L: 219 :L:R6.5 MURINE MONOCLONAL ANTIBODY FAB FRAGMENT:MOUSE (MUS MUSCULUS): 2.80:-1.00
DVVMTQSPLSLPVSLGDQASISCRSSQSLVHSNGNNYLHWYLQKSGQAPKLLIYKVSNRFSGVPDRFSGSGSGTD
FTLKISRVEAEDLGVYFCSQSTHVPLTFGGGTKLEIKRADAAPTVSIFPPSSEQLTSGGASVVCFLNNFYPKDIN
VKWKIDGSERQNGVLNSWTDQDSKDSTYSMSSTLTLTKDEYERHNSYTCEATHKTSTSPIVKSFNRNEC*
>P1;1rmfH
structureX:1rmf:   1 :H: 216 :H:R6.5 MURINE MONOCLONAL ANTIBODY FAB FRAGMENT:MOUSE (MUS MUSCULUS): 2.80:-1.00
QVQLQQSGPELVRPGVSVKISCKGSGYTFIDYAIHWVKESHAKSLEWIGVISAYSGDTNYNQKFKGKATMTVDKS
SNTAYLELARLTSEDSAIYYCARGGWLLLSFDYWGQGTTLTVSSAKTTAPSVTPLAPVCGDTTGSSVTLGVLVKG
YFPEPVTLTWNSGSLSSGVHTFPAVLQSDLYTLSSSVTVTSSTWPSQSITCNVAHPASSTKVDKKI*
>P1;1rnv
structureX:1rnv:   1 : : 124 : :RIBONUCLEASE S (E.C.3.1.27.5) (PH 4.75):BOVINE (BOS TAURUS) PANCREAS: 1.60:-1.00
KETAAAKFERQHMDSNYCNQMMKSRNLTKDRCKPVNTFVHESLADVQAVCSQKNVACKNGQTNCYQSYSTMSITD
CRETGSSKYPNCAYKTTQANKHIIVACEGNPYVPVHFDASV*
>P1;1rof
structureN:1rof:   1 : :  60 : :MOL_ID  1;  MOLECULE  FERREDOXIN;  CHAIN  NULL;  ENGINEERED  YES;  OTHER_DETAIL:MOL_ID  1;  ORGANISM_SCIENTIFIC  THERMOTOGA MARITIMA;  EXPRESSION_SYSTEM  ESCHE:-1.00:-1.00
MKVRVDADACIGCGVCENLCPDVFQLGDDGKAKVLQPETDLPCAKDAADSCPTGAISVEE*
>P1;1rafA
structureX:1raf:   1 :A: 310 :A:ASPARTATE TRANSCARBAMOYLASE (E.C.2.1.3.2) (ASPARTATE  CARBAMOYLTRANSFERASE) (T:(ESCHERICHIA COLI): 2.50:-1.00
ANPLYQKHIISINDLSRDDLNLVLATAAKLKANPQPELLKHKVIASCFFEASTRTRLSFETSMHRLGASVVGFSD
SANTSLGKKGETLADTISVISTYVDAIVMRHPQEGAARLATEFSGNVPVLNAGDGSNQHPTQTLLDLFTIQETQG
RLDNLHVAMVGDLKYGRTVHSLTQALAKFDGNRFYFIAPDALAMPQYILDMLDEKGIAWSLHSSIEEVMAEVDIL
YMTRVQKERLDPSEYANVKAQFVLRASDLHNAKANMKVLHPLPRVDEIATDVDKTPHAWYFQQAGNGIFARQALL
ALVLNRDLVL*
>P1;1rafB
structureX:1raf:   1 :B: 153 :B:ASPARTATE TRANSCARBAMOYLASE (E.C.2.1.3.2) (ASPARTATE  CARBAMOYLTRANSFERASE) (T:(ESCHERICHIA COLI): 2.50:-1.00
MTHDNKLQVEAIKRGTVIDHIPAQIGFKLLSLFKLTETDQRITIGLNLPSGEMGRKDLIKIENTFLSEDQVDQLA
LYAPQATVNRIDNYEVVGKSRPSLPERIDNVLVCPNSNCISHAEPVSSSFAVRKRANDIALKCKYCEKEFSHNVV
LAN*
>P1;1rafC
structureX:1raf:   1 :C: 310 :C:ASPARTATE TRANSCARBAMOYLASE (E.C.2.1.3.2) (ASPARTATE  CARBAMOYLTRANSFERASE) (T:(ESCHERICHIA COLI): 2.50:-1.00
ANPLYQKHIISINDLSRDDLNLVLATAAKLKANPQPELLKHKVIASCFFEASTRTRLSFETSMHRLGASVVGFSD
SANTSLGKKGETLADTISVISTYVDAIVMRHPQEGAARLATEFSGNVPVLNAGDGSNQHPTQTLLDLFTIQETQG
RLDNLHVAMVGDLKYGRTVHSLTQALAKFDGNRFYFIAPDALAMPQYILDMLDEKGIAWSLHSSIEEVMAEVDIL
YMTRVQKERLDPSEYANVKAQFVLRASDLHNAKANMKVLHPLPRVDEIATDVDKTPHAWYFQQAGNGIFARQALL
ALVLNRDLVL*
>P1;1rafD
structureX:1raf:   1 :D: 153 :D:ASPARTATE TRANSCARBAMOYLASE (E.C.2.1.3.2) (ASPARTATE  CARBAMOYLTRANSFERASE) (T:(ESCHERICHIA COLI): 2.50:-1.00
MTHDNKLQVEAIKRGTVIDHIPAQIGFKLLSLFKLTETDQRITIGLNLPSGEMGRKDLIKIENTFLSEDQVDQLA
LYAPQATVNRIDNYEVVGKSRPSLPERIDNVLVCPNSNCISHAEPVSSSFAVRKRANDIALKCKYCEKEFSHNVV
LAN*
>P1;1ravA
structureX:1rav:   2 :A: 125 :A:MOL_ID  1;  MOLECULE  AVIDIN;  CHAIN  A, B;  ENGINEERED  REFOLDING PROCEDURE NE:MOL_ID  1;  ORGANISM_SCIENTIFIC  GALLUS GALLUS;  ORGANISM_COMMON  CHICKEN;  CEL: 2.20:-1.00
RKCSLTGKWTNDLGSNMTIGAVNSRGEFTGTYITAVTATSNEIKESPLHGTENTINKRTQPTFGFTVNWKFSEST
TVFTGQCFIDRNGKEVLKTMWLLRSSVNDIGDDWKATRVGINIFTRLRT*
>P1;1ravB
structureX:1rav:   2 :B: 125 :B:MOL_ID  1;  MOLECULE  AVIDIN;  CHAIN  A, B;  ENGINEERED  REFOLDING PROCEDURE NE:MOL_ID  1;  ORGANISM_SCIENTIFIC  GALLUS GALLUS;  ORGANISM_COMMON  CHICKEN;  CEL: 2.20:-1.00
RKCSLTGKWTNDLGSNMTIGAVNSRGEFTGTYITAVTATSNEIKESPLHGTENTINKRTQPTFGFTVNWKFSEST
TVFTGQCFIDRNGKEVLKTMWLLRSSVNDIGDDWKATRVGINIFTRLRT*
>P1;1rbf
structureX:1rbf:  21 : : 124 : :RIBONUCLEASE S (E.C.3.1.27.5) MUTANT WITH MET 13 REPLACED BY  GLY (M13G):BOVINE (BOS TAURUS) PANCREAS: 1.80:-1.00
SSSNYCNQMMKSRNLTKDRCKPVNTFVHESLADVQAVCSQKNVACKNGQTNCYQSYSTMSITDCRETGSSKYPNC
AYKTTQANKHIIVACEGNPYVPVHFDASV*
>P1;1rbv
structureX:1rbv:   1 : : 155 : :RIBONUCLEASE H (E.C.3.1.26.4) MUTANT WITH LYS 95 REPLACED  BY ALA (K95A):(ESCHERICHIA COLI): 1.80:-1.00
MLKQVEIFTDGSCLGNPGPGGYGAILRYRGREKTFSAGYTRTTNNRMELMAAIVALEALKEHCEVILSTDSQYVR
QGITQWIHNWKKRGWKTADAKPVKNVDLWQRLDAALGQHQIKWEWVKGHAGHPENERCDELARAAAMNPTLEDTG
YQVEV*
>P1;1rcf
structureX:1rcf:   1 : : 169 : :FLAVODOXIN COMPLEXED WITH FLAVIN MONONUCLEOTIDE (FMN):ANABAENA (ANABAENA) STRAIN 7120  RECOMBINANT FORM EXPRESSED IN (ESCHERICHIA COL: 1.40:-1.00
SKKIGLFYGTQTGKTESVAEIIRDEFGNDVVTLHDVSQAEVTDLNDYQYLIIGCPTWNIGELQSDWEGLYSELDD
VDFNGKLVAYFGTGDQIGYADNFQDAIGILEEKISQRGGKTVGYWSTDGYDFNDSKALRNGKFVGLALDEDNQSD
LTDDRIKSWVAQLKSEFGL*
>P1;1rdv
structureX:1rdv:   1 : :  52 : :MOL_ID  1;  MOLECULE  RUBREDOXIN;  CHAIN  NULL;  BIOLOGICAL_UNIT  MONOMER:MOL_ID  1;  ORGANISM_SCIENTIFIC  DESULFOVIBRIO VULGARIS;  STRAIN  MIYAZAKI F;: 2.00:-1.00
MKKYVCTVCGYEYDPAEGDPDNGVKPGTAFEDVPADWVCPICGAPKSEFEPA*
>P1;1refA
structureX:1ref:   2 :A: 190 :A:MOL_ID  1;  MOLECULE  ENDO-1,4-BETA-XYLANASE II;  CHAIN  A, B;  SYNONYM  XYNII;:MOL_ID  1;  ORGANISM_SCIENTIFIC  TRICHODERMA REESEI;  STRAIN  TRICHODERMA REESE: 1.60:-1.00
TIQPGTGYNNGYFYSYWNDGHGGVTYTNGPGGQFSVNWSNSGNFVGGKGWQPGTKNKVINFSGSYNPNGNSYLSV
YGWSRNPLIEYYIVENFGTYNPSTGATKLGEVTSDGSVYDIYRTQRVNQPSIIGTATFYQYWSVRRNHRSSGSVN
TANHFNAWAQQGLTLGTMDYQIVAVEGYFSSGSASITVS*
>P1;1refB
structureX:1ref:   2 :B: 190 :B:MOL_ID  1;  MOLECULE  ENDO-1,4-BETA-XYLANASE II;  CHAIN  A, B;  SYNONYM  XYNII;:MOL_ID  1;  ORGANISM_SCIENTIFIC  TRICHODERMA REESEI;  STRAIN  TRICHODERMA REESE: 1.60:-1.00
TIQPGTGYNNGYFYSYWNDGHGGVTYTNGPGGQFSVNWSNSGNFVGGKGWQPGTKNKVINFSGSYNPNGNSYLSV
YGWSRNPLIEYYIVENFGTYNPSTGATKLGEVTSDGSVYDIYRTQRVNQPSIIGTATFYQYWSVRRNHRSSGSVN
TANHFNAWAQQGLTLGTMDYQIVAVEGYFSSGSASITVS*
